# CodeProject.AI Server
#
# Docker file for x86_64 GPU (CUDA, no cuDNN) enabled image
#
# ASSUMPTION: This is being build from the root directory of the solution. This
# is set in the build_docker script as the last param to the docker buildx command,
# namely the "../..". This takes us from /Installers/Docker to /. and then this
# image file proceeds
#
# WARNING: This image does not have cuDNN. .NET ONNX runtime for GPU doesn't
# work on this image - it will fallback to CPU.

# INITIAL SETUP ===============================================================
ARG CUDAVERSION=11.7.1
ARG CUDAVMAJOR=11

FROM nvidia/cuda:$CUDAVERION-runtime-ubuntu22.04 AS base
# Any of these will cause YOLO 6.2 to lockup. They don't add any perf gain
# FROM nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu22.04 AS base
# FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04 AS base
# FROM nvidia/cuda:12.0.1-cudnn8-runtime-ubuntu22.04 AS base

WORKDIR /app

# Replace the sudo command, which doesn't exist in this image, with a noop so
# our scripts, which do contain sudo calls, will work
RUN if ! type sudo 2>/dev/null; then echo "#!/bin/sh\n\${@}" > /usr/sbin/sudo; chmod +x /usr/sbin/sudo; fi

# Environment vars ------------------------------------------------------------

ENV ASPNETCORE_URLS=http://+:32168;http://+:5000

# The simple log format is easier on my brain than json
ENV LOGGING__CONSOLE__FORMATTERNAME=simple

# Magic that was being done by the Microsoft ASP.NET base image that we aren't using anymore
ENV DOTNET_RUNNING_IN_CONTAINER=true

# noninteractive frontend means no prompts or questions are asked and whenever a call requires an
# answer, the default will be used. Installs will be non-interrupted and so won't hang. The Python
# installs, for instance, require this in this current environment
ENV DEBIAN_FRONTEND noninteractive

# Let the modules know CUDA support should be enabled
ENV USE_CUDA=True

# Setup the ports -------------------------------------------------------------

EXPOSE 5000
EXPOSE 32168/tcp
EXPOSE 32168/udp

# Add some labels to the container --------------------------------------------

ARG VERSION
ENV VERSION=${VERSION}

LABEL "Application"="CodeProject.AI Server"
LABEL "Publisher"="CodeProject Solutions Inc"
LABEL "Version"="${VERSION}"
LABEL "Target"="Generic Linux x86_64 CPU"
LABEL "Description"="CodeProject.AI Server with CPU-only processing."

# Install required libraries --------------------------------------------------

# Install packages. In order:
#
# Required for SkiaSharp
#   libfontconfig1
# Required for System.Drawing
#   libgdplus
#   libjpeg-dev (maybe?)
#   zlib1g-dev (maybe?)
# Needed for opencv-python
#   ffmpeg libsm6 libxext6 libc6-dev
# So we can query glxinfo for GPU info
#   mesa-utils
# So we can install modules
#   curl jq unzip wget rsync ca-certificates (ca-certificates so we can do --no-check-certificate, jq for json parsing)
# This stops the "lsmod: not found" error
#   kmod

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libfontconfig1  \
    libgdiplus      \
    libjpeg-dev     \
    zlib1g-dev      \
                    \
    ffmpeg          \
    libc6-dev       \
    libsm6          \
    libxext6        \
                    \
    mesa-utils      \
                    \
    ca-certificates \
    curl            \
    jq              \
    rsync           \
    unzip           \
    wget            \
                    \
    psmisc          \
                    \
    kmod            > /dev/null

    # Not needed. Probably.
    # apt-utils


# .NET 7 ----------------------------------------------------------------------

# Update packages and install NET7
RUN wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb && \
    apt update && \
    apt install aspnetcore-runtime-7.0 -y

# Setup Python ----------------------------------------------------------------

RUN apt-get install software-properties-common -y && add-apt-repository ppa:deadsnakes/ppa -y

# This (currently) installs python3.8 as a dependency. It could be in the future
# that a different version of python is installed instead, in which case we may
# need to pin the installed python version.
RUN apt-get install python3-pip -y && apt-get install python3-apt -y

# Install Python3.8, distutils and dev tools (so packages can be built if needed)
# and pip install so we can install python packages
RUN apt-get install python3.8 -y && \
    apt-get install python3.8-distutils -y && \
    apt-get install python3.8-dev -y && \ 
    python3.8 -m pip install --upgrade setuptools && \
    python3.8 -m pip install --upgrade pip

# install virtual env tools
RUN apt install python3-pip python3-setuptools python3.8-venv -y && \
    python3.8 -m pip install virtualenv virtualenvwrapper

# Install Python3.9, distutils and dev tools (so packages can be built if needed)
# and pip install so we can install python packages. We don't need this for the
# built in modules, but we know we have downloadable modules that could use Python3.9
# so we preempt the need.
RUN apt-get install python3.9 -y && \
   apt-get install python3.9-distutils -y && \
   apt-get install python3.9-dev -y && \ 
   python3.9 -m pip install --upgrade setuptools && \
   python3.9 -m pip install --upgrade pip

#RUN apt python3.9-venv -y
RUN python3.9 -m pip install virtualenv virtualenvwrapper


# Build the source ------------------------------------------------------------

# Use a build container
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /src

# This copies everything, or tries to. If you have a file anywhere under /src
# that's locked or not readable or huge, this wholesale copying will be blocked
# and your image build will fail.
# COPY . .

# Instead, let's copy over only that which we need.
RUN mkdir src
RUN mkdir src/modules
RUN mkdir src/runtimes

#### Just copy the bits we need to comipile with NET 7.0 SDK ####
COPY src/server/                            src/server/
COPY src/SDK/                               src/SDK/
COPY src/modules/ObjectDetectionYOLOv5Net/  src/modules/ObjectDetectionYOLOv5Net/

#### These are copied later so not required here ####
# COPY src/modules/FaceProcessing/            src/modules/FaceProcessing/
# COPY src/modules/ObjectDetectionCoral       src/modules/ObjectDetectionCoral/
# COPY src/modules/ObjectDetectionYOLOv5-6.2/ src/modules/ObjectDetectionYOLOv5-6.2/
# COPY src/server/install.sh                  src/server/.
# COPY src/setup.sh                           src/
# RUN ls -la /src/*


# Doing this separately here means we have a cached layer. However, restore was
# not always successful, and in any case is done as part of the build. Not worth it
# RUN dotnet restore "src/server/server.csproj"

# Build and publish Server
WORKDIR "/src/src/server"
RUN dotnet publish "Server.csproj" -c Release --no-self-contained --force -o /app/publish/server

# Build and publish .NET modules, copy over docker-specific modulesettings, and 
# then copy over models

# NOTE: For modules that we're installing directly into the Docker image, we will
#       use the /preinstalled-modules folder, not the /modules folder. This is
#       because we are asking users to mount a folder on their host machine mapped
#       to the /modules folder in this docker image. When they do that, anything
#       in the /modules folder in this image disappears and is replaced by the 
#       contents of the folder they mounted.
#
#       Two solutions:
#         1. We install pre-installed modules in a different folder (this is what
#            we're doing). The modules can still be uninstalled, and if
#            re-installed, they will be installed in the modules directory as 
#            "not preinstalled".
#         2. We work out how to mount a folder in a way that makes the stuff we've
#            already installed still be visible, while also allowing us to add
#            installed modules to the folder. This  probably involves volumes

WORKDIR "/src/src/modules/ObjectDetectionYOLOv5Net"
RUN dotnet publish ObjectDetectionYOLOv5Net.csproj -c Release --no-self-contained /p:DefineConstants=GPU_CUDA \
                   --force -o /app/publish/preinstalled-modules/ObjectDetectionYOLOv5Net/bin &&               \
    mv -f /app/publish/preinstalled-modules/ObjectDetectionYOLOv5Net/bin/modulesettings.*                     \
          /app/publish/preinstalled-modules/ObjectDetectionYOLOv5Net/  &&                                     \
    mv -f /app/publish/preinstalled-modules/ObjectDetectionYOLOv5Net/modulesettings.docker.build.json         \
          /app/publish/preinstalled-modules/ObjectDetectionYOLOv5Net/modulesettings.docker.json > /dev/null

# TODO: Grab these assets from our S3 bucket. Otherwise we have to ensure we've done a Dev setup on
#       the local machine first, to ensure these files are present
COPY [ "/src/modules/ObjectDetectionYOLOv5Net/assets", "/app/publish/preinstalled-modules/ObjectDetectionYOLOv5Net/assets" ]
COPY [ "/src/modules/ObjectDetectionYOLOv5Net/custom-models", "/app/publish/preinstalled-modules/ObjectDetectionYOLOv5Net/custom-models" ]

# And ensure required assets are copied over. 
COPY [ "/src/modules/ObjectDetectionYOLOv5Net/explore.html", "/app/publish/preinstalled-modules/ObjectDetectionYOLOv5Net" ]


# Move non-compiled code (Python, script) into place --------------------------

WORKDIR /src

COPY ["src/SDK/Python", "/app/publish/SDK/Python"]
COPY ["src/server/install.sh", "/app/publish/server/install.sh"]
RUN rm -rf /app/publish/SDK/Python/__pycache__

COPY ["src/SDK/Scripts", "/app/publish/SDK/Scripts"]
COPY ["src/setup.sh", "/app/publish/setup.sh"]

# We need some way to tell the server that for modules built into the Docker
# image, the venv will be in one place, but for modules downloaded at runtime, 
# the venv for the module will be in a different place.
#
# We do this by having a modulesettings.docker.build.json file that has the
# settings for modules pre-installed into the image. this build.json file is 
# copied into the image and renamed to just .docker.json at Docker build time,
# and then when the module loads up, everything works.
# 
# If the module were downloaded and installed during runtime, then the usual 
# modulesettings.linux.json would be used, and then modulesettings.docker.json
# would then be loaded (if it existed). The modulesettings.docker.build.json 
# file would be ignored.
#
# This enables us to have a modulesettings for inside a docker image, and module
# settings for modules outside the docker image.

COPY ["src/modules/FaceProcessing/", "/app/publish/preinstalled-modules/FaceProcessing"]
RUN mv  -f "/app/publish/preinstalled-modules/FaceProcessing/modulesettings.docker.build.json" "/app/publish/preinstalled-modules/FaceProcessing/modulesettings.docker.json"
RUN rm -rf "/app/publish/preinstalled-modules/FaceProcessing/intelligencelayer/__pycache__" && \
    rm -f /app/publish/preinstalled-modules/FaceProcessing/*.zip /app/publish/preinstalled-modules/FaceProcessing/package.bat /app/publish/preinstalled-modules/FaceProcessing/*.pyprog

COPY ["src/modules/ObjectDetectionYOLOv5-6.2/", "/app/publish/preinstalled-modules/ObjectDetectionYOLOv5-6.2"]
RUN mv -f "/app/publish/preinstalled-modules/ObjectDetectionYOLOv5-6.2/modulesettings.docker.build.gpu.json" "/app/publish/preinstalled-modules/ObjectDetectionYOLOv5-6.2/modulesettings.docker.json"
RUN rm -rf /app/publish/preinstalled-modules/ObjectDetectionYOLOv5-6.2/__pycache__ && \
    rm -f /app/publish/preinstalled-modules/ObjectDetectionYOLOv5-6.2/*.zip /app/publish/preinstalled-modules/ObjectDetectionYOLOv5-6.2/package.bat /app/publish/preinstalled-modules/ObjectDetectionYOLOv5-6.2/*.pyprog

# Move assets into place ------------------------------------------------------

# We'll zip up the test images and move the zip to the server wwwroot directory 
# so it can be downloaded from the API server at runtime

# These are embedded in the Docker image, and accessible via an HTTP call. If you
# know the right address... (diabled for now)

# COPY ["demos/TestData", "/app/publish/demos/TestData"]
# WORKDIR "/src/demos/TestData"
# RUN apt-get update -y && apt-get upgrade -y &&  apt-get install -y zip
# RUN zip -r testdata.zip . && mv testdata.zip /app/publish/server/wwwroot


# CREATE THE FINAL IMAGE ======================================================

FROM base AS final

# Move published server and modules into place --------------------------------

WORKDIR /app
COPY --from=build /app/publish .

# Install required Python packages --------------------------------------------

# See https://towardsdatascience.com/how-to-shrink-numpy-scipy-pandas-and-matplotlib-for-your-data-product-4ec8d7e86ee4
# for a discussion on reducing PIP install sizes. That article is woefully out of date, with the
# --compile and --global-option now deprecated, the CLFAGS to nothing, but the --no-cache-dir does help

RUN python3.8 -m pip --no-cache-dir install \
    -r /app/SDK/Python/requirements.txt \
    -r /app/preinstalled-modules/FaceProcessing/requirements.linux.cuda$CUDAMAJOR.txt \
    -r /app/preinstalled-modules/ObjectDetectionYOLOv5-6.2/requirements.linux.cuda$CUDAMAJOR.txt

RUN python3.9 -m pip --no-cache-dir install \
    -r /app/SDK/Python/requirements.txt 

# Add folder for storing persisted user data. This should be mapped to a folder
# on the host
RUN mkdir --parents /etc/codeproject/ai

# Add folder for storing installation of additional modules.
RUN mkdir --parents /app/downloads/modules /app/modules

# For debugging the live container using VS Code
RUN mkdir /app/.vscode
COPY [ "/.vscode/launch.docker.json", "/app/.vscode/launch.json" ]
COPY [ "/.vscode/tasks.docker.json", "/app/.vscode/tasks.json" ]

# Start the server
WORKDIR /app/server
ENTRYPOINT ["./CodeProject.AI.Server"]
